# Generated by Django 4.2.2 on 2023-08-18 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='recorded_by',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='approved',
            field=models.BooleanField(choices=[(0, 'Pending'), (1, 'Approved')], default=0),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.business'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='line_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_line_manager', to='manager.managerprofile'),
        ),
        migrations.DeleteModel(
            name='SickLeave',
        ),
        migrations.DeleteModel(
            name='Timesheet',
        ),
    ]
