# Generated by Django 4.2.2 on 2023-06-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='worked_hours',
            field=models.CharField(max_length=54, null=True),
        ),
    ]
