# Generated by Django 4.2.2 on 2023-06-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employeeprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='clocking_time',
            field=models.DateTimeField(null=True),
        ),
    ]
