# Generated by Django 4.2.2 on 2023-07-09 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0002_timesheet_worked_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='worked_hours',
        ),
        migrations.AddField(
            model_name='business',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.business'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.business'),
        ),
        migrations.DeleteModel(
            name='SickLeave',
        ),
    ]
