# Generated by Django 4.2.2 on 2023-08-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_delete_business_remove_timesheet_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
