# Generated by Django 4.2.2 on 2023-06-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_timesheet_clocking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
