# Generated by Django 4.2.2 on 2023-07-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_timesheet_worked_hours_business_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
