# Generated by Django 4.2.2 on 2023-08-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employeeprofile_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
