# Generated by Django 4.2.2 on 2023-07-09 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_business_business_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='name',
            new_name='business_name',
        ),
    ]
