# Generated by Django 4.2.2 on 2023-07-30 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_managerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='approved',
            field=models.BooleanField(choices=[(0, 'Pending'), (1, 'Approved')], default=0),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='line_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_line_manager', to='employees.managerprofile'),
        ),
    ]
