# Generated by Django 4.2.2 on 2023-09-23 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_us',
            new_name='Contact',
        ),
    ]
