# Generated by Django 4.2.2 on 2023-09-24 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employeeprofile_approved'),
        ('manager', '0002_alter_managerprofile_company'),
        ('contact', '0002_rename_contact_us_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employeeprofile'),
        ),
        migrations.AddField(
            model_name='contact',
            name='managers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.managerprofile'),
        ),
        migrations.AddField(
            model_name='reply',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employeeprofile'),
        ),
        migrations.AddField(
            model_name='reply',
            name='managers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.managerprofile'),
        ),
    ]
