# Generated by Django 4.2.2 on 2023-09-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_employee_contact_managers_reply_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='managers',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='employee',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
