# Generated by Django 4.2.2 on 2023-11-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_managerprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
