# Generated by Django 4.2.2 on 2023-11-18 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_managerprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerprofile',
            name='email',
        ),
    ]
